development:
  adapter: postgresql
  database: anagram_dev
  pool: 5
  host: localhost
  username: ruby
  password: 123456789
    
test:
  adapter: postgresql
  database: anagram_test
  pool: 5
  host: localhost
  username: ruby
  password: 123456789

production:
  url: <%= ENV['DATABASE_URL'] %>
  