development:
  adapter: postgresql
  database: anagram_dev
  pool: 5
  host: localhost
  username: <%= ENV["APP_POSTGRES_USER"] %>
  password: <%= ENV["APP_POSTGRES_PASSWORD"] %>
    
test:
  adapter: postgresql
  database: anagram_test
  pool: 5
  host: localhost
  username: <%= ENV["APP_POSTGRES_USER"] %>
  password: <%= ENV["APP_POSTGRES_PASSWORD"] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  